### ISSUE TITLE
Drop support for Node 6 and 8

### ISSUE THREAD

**Issue by artlogic** [artlogic/nabs#24]
Node 6 is no longer supported and Node 8 won't be supported in 2.5 months. Let's only support Node 10 and above. Places where this needs to be changed:
* .circleci/config.yml
* README.md
* package.json

**Comment by MgenGlder** [comment]
On it!

**Comment by artlogic** [comment]
@MgenGlder All yours! Thanks!

**Comment by artlogic** [comment]
Closed by #26.
