### ISSUE TITLE
WIP branch for prototype

### ISSUE THREAD

**Issue by texastoland** [artlogic/nabs#4]
I propose a WIP branch. I recommend `wip/next` (or `wip/{prototype, types, texas, tejano, gatito, or you pick}`) so I can rebase guilt-free. This way we can discuss minimally, merge, then continue bikeshedding with no lock-in. You can do it [right from GitHub](https://blog.github.com/2013-01-09-create-and-delete-branches/).

Flow is ready and I'll sanity check the build! I got the editor sorted. At full strictness Flow is still less strict than TS. They have a type called `empty` that spreads through the type graph like `any` except it's allowed. It's also blatantly wrong often. texastoland/nabs#6 should be quick. The original is still stashed.

**Comment by artlogic** [comment]
I'm not sure why this is needed. Is there a problem with submitting small PRs from your repo?
